// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFfYacTZAtr_ALNVku7_l-thpq1-a0Ws',
    appId: '1:355706238291:android:b29ae279a3a1f23996dda6',
    messagingSenderId: '355706238291',
    projectId: 'sotwo-f77f7',
    databaseURL: 'https://sotwo-f77f7-default-rtdb.firebaseio.com',
    storageBucket: 'sotwo-f77f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelNX_KGD8OQv7DLI7MhPRsaICJyyXiQc',
    appId: '1:355706238291:ios:f1ff17ae10eba45296dda6',
    messagingSenderId: '355706238291',
    projectId: 'sotwo-f77f7',
    databaseURL: 'https://sotwo-f77f7-default-rtdb.firebaseio.com',
    storageBucket: 'sotwo-f77f7.appspot.com',
    androidClientId: '355706238291-gm2mi0s2sfup57brjq2fllrgs4mbdidm.apps.googleusercontent.com',
    iosClientId: '355706238291-6v369382m2lv4rrt727gf6efnc7cf1h9.apps.googleusercontent.com',
    iosBundleId: 'com.sablue.sotwo',
  );

}